eureka:
  client:
    service-url:
      defaultZone: http://eureka-assist:8762/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761
management:
  context-path: /
